api_version: 1
threadsafe: yes
runtime: python27

# env: flex
# runtime: python
# entrypoint: gunicorn -b :$PORT main:wsgi

handlers:
  - url: .*
    script: main.wsgi.application

env_variables:
  DJANGO_SETTINGS_MODULE: 'main.settings'
